name: SSH Debug

on:
  push:
    branches: [production]

jobs:
  debug-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Run SSH command with debug log
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo "✅ Kết nối SSH thành công!"
            whoami
            uname -a
          debug: true
          command_timeout: 5m
